# Generated by Django 5.2.3 on 2025-06-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_avatar_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://www.iconpacks.net/icons/2/free-user-icon-3296-thumb.png'),
        ),
    ]
