# Generated by Django 5.2.3 on 2025-06-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_course_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['sequence_number']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'sequence_number')},
        ),
    ]
