# Generated by Django 5.2.3 on 2025-06-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_enrollment_completed_lessons_lessoncompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
