# Generated by Django 5.2.3 on 2025-06-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_enrollment_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_receipt_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
