# Generated by Django 5.2.3 on 2025-06-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_enrollment_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='payment_intent_id',
        ),
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.URLField(),
        ),
    ]
